name: Espinho
description: Blogging about my learnings and ideas
meta_description: "Espinho's personal blog"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://espinhogr.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'espinhogrgithubio'

# Details for the RSS feed generator
url:            'http://espinhogr.github.io'
author:         'Espinho'
authorTwitter:  'espinhogr'

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
